### ISSUE TITLE
compile errors 

### ISSUE THREAD

**Issue by vern59** [hjmcnew/esphome-hs2xx3a-custom-component#20]
validate works fine no problems but compile fails
my YAML

esphome:
  name: esp32-sensor-farm1

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    
packages:

  remote_package:
    url: https://github.com/hjmcnew/esphome-hs2xx3a-custom-component
    ref: release
    files: [packages/uart.yml, packages/leapmmw_sensor.yml]

substitutions:

  device_name: leapmmw
  # This will vary based on your board
  uart_tx_pin: GPIO17
  
  # This will vary based on your board
  uart_rx_pin: GPIO16
  
  # This will vary based on your board
  gpio_pin: GPIO19

#header_file: /config/esphome/leapmmw_sensor.h

I left out wifi password and ssid

Failed compile message

Compiling /data/esp32-sensor-farm1/.pioenvs/esp32-sensor-farm1/src/esphome/components/api/api_connection.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/esp32-sensor-farm1/.pioenvs/esp32-sensor-farm1/src/esphome/components/api/api_frame_helper.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
Compiling /data/esp32-sensor-farm1/.pioenvs/esp32-sensor-farm1/src/esphome/components/api/api_pb2.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/esp32-sensor-farm1/.pioenvs/esp32-sensor-farm1/src/esphome/components/api/api_connection.cpp.o] Error 127
*** [/data/esp32-sensor-farm1/.pioenvs/esp32-sensor-farm1/src/esphome/components/api/api_frame_helper.cpp.o] Error 127
*** [/data/esp32-sensor-farm1/.pioenvs/esp32-sensor-farm1/src/esphome/components/api/api_pb2.cpp.o] Error 127
Compiling /data/esp32-sensor-farm1/.pioenvs/esp32-sensor-farm1/src/esphome/components/api/api_pb2_service.cpp.o
sh: 1: xtensa-esp32-elf-g++: not found
*** [/data/esp32-sensor-farm1/.pioenvs/esp32-sensor-farm1/src/esphome/components/api/api_pb2_service.cpp.o] Error 127
========================== [FAILED] Took 5.23 seconds ==========================

**Comment by hjmcnew** [comment]
Seems to be working on the latest ESPHome. See https://github.com/hjmcnew/esphome-hs2xx3a-custom-component/actions/runs/6092636824/job/16531072244. Marking this as closed. Please open a new issue if you encounter any other issues.
