### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Langelus** [hjmcnew/esphome-hs2xx3a-custom-component#23]
Since update of ESPHome to version 2023.4.0 I get this error when trying to compile the firmware
--------------

Processing mps-vardagsrummet (board: esp32dev; framework: arduino; platform: platformio/espressif32 @ 5.3.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
|-- Wire @ 2.0.0
Compiling /data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/src/main.cpp.o
Compiling /data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/lib64d/WiFi/WiFiScan.cpp.o
Compiling /data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/lib64d/WiFi/WiFiServer.cpp.o
Compiling /data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/lib64d/WiFi/WiFiUdp.cpp.o
In file included from src/main.cpp:116:
src/leapmmw_sensor.h: In function 'void publishTarget(std::__cxx11::string, float, float)':
src/leapmmw_sensor.h:9:33: error: 'class esphome::StringRef' has no member named 'substr'; did you mean 'c_str'?
     if(name.size() > 10 && name.substr(0, 8) == target) {
                                 ^~~~~~
                                 c_str
src/leapmmw_sensor.h:10:15: error: 'class esphome::StringRef' has no member named 'substr'; did you mean 'c_str'?
       if(name.substr(9, 3) == "dis") {
               ^~~~~~
               c_str
src/leapmmw_sensor.h:12:22: error: 'class esphome::StringRef' has no member named 'substr'; did you mean 'c_str'?
       } else if(name.substr(9, 3) == "SNR") {
                      ^~~~~~
                      c_str
Compiling /data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/lib915/ESPmDNS/ESPmDNS.cpp.o
Archiving /data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/lib64d/libWiFi.a
Compiling /data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/libbc6/Update/HttpsOTAUpdate.cpp.o
Compiling /data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/libbc6/Update/Updater.cpp.o
Compiling /data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/lib106/libsodium/crypto_aead/chacha20poly1305/sodium/aead_chacha20poly1305.c.o
*** [/data/mps-vardagsrummet/.pioenvs/mps-vardagsrummet/src/main.cpp.o] Error 1
========================== [FAILED] Took 2.57 seconds ==========================

**Comment by janprive** [comment]
I get the same error. The Yaml is correct.

**Comment by crlogic** [comment]
Replace `auto name` in the [leapmmw_sensor.h](https://github.com/hjmcnew/esphome-hs2xx3a-custom-component/blob/main/leapmmw_sensor.h) with `std::string` and it will compile.  Pinging @hjmcnew for merge review/release

**Comment by baerrs** [comment]
this worked for me

**Comment by janprive** [comment]
Thank you very much!!! Working now!

**Comment by hjmcnew** [comment]
> Replace `auto name` in the [leapmmw_sensor.h](https://github.com/hjmcnew/esphome-hs2xx3a-custom-component/blob/main/leapmmw_sensor.h) with `std::string name` and it will compile.  Pinging @hjmcnew for merge review/release

Reviewed, merged, released in April 26. Marking this resolved.
