### ISSUE TITLE
Compile error on latest esp home

### ISSUE THREAD

**Issue by addelovein** [hjmcnew/esphome-hs2xx3a-custom-component#27]
In file included from src/main.cpp:316:
src/leapmmw_sensor.h: In function 'void publishTarget(std::__cxx11::string, float, float)':
src/leapmmw_sensor.h:9:33: error: 'class esphome::StringRef' has no member named 'substr'; did you mean 'c_str'?
     if(name.size() > 10 && name.substr(0, 8) == target) {
                                 ^~~~~~

**Comment by hjmcnew** [comment]
Seems like a dupe of https://github.com/hjmcnew/esphome-hs2xx3a-custom-component/issues/23. Can you grab the latest code and try again?
